#Broadcastingning asosiy qoidasi

NumPy shape’larni:

      | o‘ngdan chapga 

solishtiradi.

Va dimensionlar:

teng bo‘lsa ✅
yoki bittasi 1 bo‘lsa ✅
aks holda ❌ error



In [ ]:
#Row Broadcasting

import numpy as np

arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9] ##(3,3). yani 3ta row va 3 ta column
])

#bonus = np.array([10,20,30,40]) #(4, ) 1D array yani 4 element
bonus = np.array([[10], [20], [30]]) #Agar har row’ga alohida bonus bermoqchi bo‘lsang:

print(arr + bonus)

#To‘g‘ri ishlashi uchun bonus column soniga teng bo‘lishi kerak

[[11 12 13]
 [24 25 26]
 [37 38 39]]


In [14]:
arr.shape

(4, 3)

In [20]:
sales = np.array([
    [200,150,300],
    [220,170,310],
    [250,160,290]
])

tax = np.array([
    [10],
    [20],
    [30]
])

print(sales + tax)

[[210 160 310]
 [240 190 330]
 [280 190 320]]


In [ ]:
#Broadcasting (sehri)
matrix = np.array([[1, 2, 3], [4, 5, 6]])
vector = np.array([10, 20, 30])

result = matrix + vector
# [[11, 22, 33], [14, 25, 36]]
#Turli o'lchamdagi arraylarni "kengaytirib" ishlash.

###Column Broadcastiing

In [19]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [4,5,6]
])

bonus = np.array([
    [100],
    [200],
    [4]
])

print(arr + bonus)

[[101 102 103]
 [204 205 206]
 [  8   9  10]]


###| (3, 3) + (3,)    ✅ row broadcasting |
###| (3, 3) + (3, 1)  ✅ column broadcasting |
###| (3, 3) + (2,)    ❌ xato |

In [21]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

x = np.array([10, 20, 30])

print(arr + x)

[[11 22 33]
 [14 25 36]]


In [23]:
import numpy as np

salary = np.array([3000, 5000, 7000])

result=salary - salary.mean()

print(result)


# 5000

[-2000.     0.  2000.]
