In [10]:
import numpy as np

arr = np.array([35,20,30,1,50])

indexing = arr[[0,2,4]] #avvalo array ichidagi unordered numberlarini oldik

print(np.sort(indexing)) # so'ng bu yerda sort qiladi

[30 35 50]


In [ ]:
matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(matrix[[0,2], [2,1]]) #row va column

[3 8]


In [12]:
arr = np.array([100,200,300,400,500])

print(arr[[4,2,0]])
print(np.sort(arr[[4,2,0]]))

[500 300 100]
[100 300 500]


In [ ]:
#Fancy va booleen
arr = np.array([10,20,30,40,50])

idx = np.array([0,2,4])

selected = arr[idx]

print(selected[selected > 20])

[10 30 50]


In [16]:
arr = np.array([1,2,3,4])

x = arr[[0,2]]

x[0] = 999

print(arr)

[1 2 3 4]


In [17]:
#view

arr = np.array([1,2,3,4])

x = arr[[0,2]]

x[0] = 999

print(arr)

[1 2 3 4]


np.concatenate()
np.vstack()
np.hstack()
np.column_stack()