np.concatenate()
np.vstack()
np.hstack()
np.column_stack()

In [1]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.concatenate([a,b]))

[1 2 3 4 5 6]


In [ ]:
#2D Concatenate
a = np.array([
    [1,2],
    [3,4]
])

b = np.array([
    [5,6]
])

print(np.concatenate([a,b], axis=0)) #vertical rows qo‘shadi.
#a.shape -> (2,2)
#b.shape -> (1,2)
#Columns soni bir xil bo‘lishi kerak

[[1 2]
 [3 4]
 [5 6]]


In [8]:
a = np.array([
    [1,2],
    [3,4]
])

b = np.array([
    [5],
    [6]
])

np.concatenate([a,b], axis=1) #garizontal col qoshadi

array([[1, 2, 5],
       [3, 4, 6]])

In [ ]:
#vstack() ← vertical stack

a = np.array([1,2,3])
b = np.array([4,5,6])

np.vstack([a,b])

#1D array’larni avtomatik 2D rowga aylantiradi.

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
#hstack() ← horizontal stack

a = np.array([1,2,3])
b = np.array([4,5,6])

np.hstack([a,b])

array([1, 2, 3, 4, 5, 6])

In [11]:
#2D
a = np.array([
 [1],
 [2]
])

b = np.array([
 [3],
 [4]
])

np.hstack([a,b])

array([[1, 3],
       [2, 4]])

In [13]:
name_id = np.array([101,102,103])
score = np.array([80,90,70])

np.column_stack([name_id, score])

array([[101,  80],
       [102,  90],
       [103,  70]])

In [15]:
a = np.array([
 [1,2],
 [3,4]
])

b = np.array([
 [5,6]
])

print(np.vstack([a,b]))

[[1 2]
 [3 4]
 [5 6]]
