👉 Array’ning shape’ini o‘zgartirish

Data o‘zgarmaydi.
Faqat structure o‘zgaradi.

In [21]:
import numpy as np

test = np.array([1,3,3,4,5,6,7,8,9,10])

print(test.shape)

##7 ta element va 1D array

(10,)


In [31]:
test_reshape = test.reshape(2,5)
print(test_reshape)

[[ 1  3  3  4  5]
 [ 6  7  8  9 10]]


In [40]:
arr = np.array([1,2,3,4,5,6,7,8,1,2,3,4,5,6,7,8])

arr.reshape(8, -1)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])