In [13]:
import numpy as np

arr = np.array([50, 10, 40, 20, 30])
#oddiy sorting
result = np.sort(arr) # lekin original array’ni o‘zgartirmaydi.
result = arr.sort()

print(result)

None


2. Descending Sort

NumPy’da direct descending yo‘q.

Senior usul:

np.sort(arr)[::-1]

Output:

[50 40 30 20 10]
[::-1] nima?

Reverse qilish.

In [14]:
np.sort(arr)[::-1] # reverse qilish uchun

array([50, 40, 30, 20, 10])

In [19]:
#2D Sorting
matrix = np.array([
    [30, 10, 20],
    [90, 30, 80]
])

np.sort(matrix) #row bo‘yicha sort qiladi.
result = np.sort(matrix, axis=0)

print(result)

[[30 10 20]
 [90 30 80]]


In [ ]:
import numpy as np

arr = np.array([[3, 22, 0, 1],[22, 12, 10, 0]])

print(np.sort(arr, axis=0)) #coulmn boyicha sort qiladi yani tepadan pastga
print(arr)

[[ 3 12  0  0]
 [22 22 10  1]]
[[ 3 22  0  1]
 [22 12 10  0]]


In [3]:
#Sort the array alphabetically:

import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [4]:
#Sort a boolean array:

import numpy as np

arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


Mental Model:


axis=0

⬆️⬇️ vertical
column operation

axis=1

⬅️➡️ horizontal
row operation

Bu axis tushunchasi:

sorting,
sum,
mean,
max,
std,

hammasida ishlatiladi.

In [18]:
#np.argmax()

#Maximum elementning INDEX’ini beradi.

arr = np.array([10, 50, 20, 80, 30])

print(np.argmax(arr)) #eng katta number index beradi
print(np.argmin(arr)) #eng kichik number index beradi
print(np.max(arr)) # eng katta number beradi
print(np.min(arr)) # eng kichik number qaytari

3
0
80
10


#SEARCH

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

#(array([3, 5, 6]),) yani bular 4 raqami bor bo'lgan indexlar

(array([3, 5, 6]),)


In [ ]:
arr = np.array([50, 10, 40, 20])

np.argsort(arr) #Chunki sorted orderdagi indexlarni qaytaradi.

arr[1] = 10
arr[3] = 20
arr[2] = 40
arr[0] = 50

array([1, 3, 2, 0])

In [ ]:
arr = np.array([70, 10, 50, 20])

print(np.argsort(arr))


[1 3 2 0]


In [36]:
sales = np.array([1200, 800, 5000, 300, 7000])

print(np.max(sales))
print(np.where(sales == 800))

7000
(array([1]),)


In [ ]:
import numpy as np

arr = np.array([10, 14, 93, 41, 8, 7])

x = arr[np.where(arr%2 == 1)] #odd numbers
x = np.where(arr%2 == 0) #even numbers

print(x)

[93 41  7]


In [40]:

#“Array sorted bo‘lib turganda yangi qiymat qayerga qo‘yilsa tartib buzilmaydi?”

#Juda muhim shart
#Array SORTED bo‘lishi kerak.
#Agar: [40,10,30] bersang — natija unreliable bo‘ladi.
arr = np.array([1, 3, 5, 7, 40,56,72])

print(np.searchsorted(arr, 50))

5


In [45]:
import numpy as np

arr = np.array([1, 3, 5, 7])

x = arr[np.searchsorted(arr, [2, 4, 6])]

print(x)

[3 5 7]


In [43]:
#side="left" va side="right" aslida duplicate qiymatlar bo‘lganda farq qiladi.
arr = np.array([1, 2, 2, 2, 3])

print(np.searchsorted(arr, 2, side= "right"))


4


In [ ]:
arr = np.array([10,  20, 30, 40])

print(np.searchsorted(arr, [15, 35]))

[1 3]
