In [1]:
from numpy import random

x = random.normal(size=(2, 3))

print(x)

[[-1.95463538 -0.72356282  2.21649751]
 [ 0.18297518  0.34250078 -0.0033954 ]]


In [2]:
from numpy import random

x = random.normal(loc=1, scale=2, size=(2, 3))

print(x)

[[-0.27057239  1.61139131  2.55007333]
 [ 1.39742099 -0.38092099  3.29749532]]
