In [1]:
from numpy import random

x = random.normal(size=(2, 3))

print(x)

[[-1.95463538 -0.72356282  2.21649751]
 [ 0.18297518  0.34250078 -0.0033954 ]]


In [2]:
from numpy import random

x = random.normal(loc=1, scale=2, size=(2, 3))

print(x)

[[-0.27057239  1.61139131  2.55007333]
 [ 1.39742099 -0.38092099  3.29749532]]


In [7]:
import numpy as np
a = np.array([[1, 2, 3],
              [4, 5, 6]])
print(np.sum(a,axis=0))
print(np.mean(a, axis=1))

[5 7 9]
[2. 5.]


In [10]:
a = np.array([100, 200, 300, 400, 500])
b = np.array([0, 1, 0, 1, 1])

getting = a[b == 1]

print(getting)



[200 400 500]
