In [15]:
import numpy as np

print(np.random.randint(1, 10))

9


In [ ]:
#Bir nechta random son
arr = np.random.randint(1, 100, size=5)

print(arr)

[68 48 19 55 24]


In [30]:
#2D random array
arr = np.random.randint(1, 10, size=(3,3))

print(arr)

[[5 5 7]
 [2 7 9]
 [3 4 7]]


In [ ]:
#rand() faqat butun sonlarni oladi
arr = np.random.rand(5)

#2D random matrix
np.random.rand(2,3)

print(arr)


[0.62746962 0.47699484 0.85480742 0.99115079 0.79064047]


In [33]:
#np.random.choice() 🔥

#Bu juda ko‘p ishlatiladi.

#Array ichidan random tanlaydi.

colors = ["Red", "Blue", "Green"]

print(np.random.choice(colors))

Blue


In [34]:
#Bir nechta tanlash
colors = ["Red", "Blue", "Green"]

print(np.random.choice(colors, size=5))

['Red' 'Green' 'Red' 'Blue' 'Blue']


In [ ]:
from numpy import random

#probability'lar yig'indisi 1 bo'lishi kerak.

x = random.choice([3, 5, 7, 9], p=[0.3, 0.1, 0.6, 0.0], size=(100))

print(x)

[3 3 7 7 7 7 3 3 7 3 3 5 7 7 5 3 7 7 3 7 7 5 3 5 3 5 7 7 7 3 7 7 3 3 7 7 7
 7 3 7 3 7 7 7 7 7 7 7 7 7 5 5 7 7 7 7 7 3 7 3 7 5 5 3 3 3 7 7 5 7 7 3 7 3
 7 3 3 5 7 7 7 3 3 7 7 3 7 3 3 3 7 7 7 7 5 3 7 5 7 5]
