View

👉 original data bilan memory share qiladi

Copy

👉 yangi mustaqil data yaratadi

In [17]:
import numpy as np

arr = np.array([1,2,3,4])

view[0] = 100
#NumPy slicing odatda VIEW qaytaradi
print(view)



[100   3   4]


In [15]:
arr = np.array([1,2,3,4])

copy_arr = arr[1:].copy()
copy_arr[1] = 888


print(copy_arr)
print(arr)

[  2 888   4]
[1 2 3 4]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base) # BASE kimmi datasidan foydalanvotganini tekshiradi
print(y.base)

None
[1 2 3 4 5]


In [23]:
arr = np.array([10,20,30,40])

a = arr[1:3]
b = arr[1:3].copy()
a[0] = 999

print(a.base)
print(b.base)

[ 10 999  30  40]
None


In [31]:
import numpy as np

original_array = np.array([1, 2, 3])

x = arr.view()
print(x)

[ 10 999  30  40]


In [ ]:
Slom

Salom berish shart