In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])


print(filt)

In [ ]:
import numpy as np

print(np.__version__)

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

In [15]:
arr = np.array([
    [[1, 2],
     [3, 4]],
    [[5, 6],
     [7, 8]]
])

print(arr.ndim)
print(arr.shape)

3
(2, 2, 2)


In [34]:
import numpy as np

arr = np.array([10, 20, 30,50,10,2,4,])

new_arr = np.ones_like(arr)
print(new_arr)

[1 1 1 1 1 1 1]


In [20]:
arrange_test = np.arange(1,10)
print(arrange_test)

[1 2 3 4 5 6 7 8 9]


###linspace → nechta son kerakligini aytasan
###arange → qadamni (step) aytasan

In [31]:
np.arange(0,10,3)

np.linspace(2,8,7)

array([2., 3., 4., 5., 6., 7., 8.])

In [27]:
np.arange(0,10,3)

array([0, 3, 6, 9])

###👉_like funksiyalar
###mavjud array’ning shape’ini olib, yangi array yaratadi





In [35]:
import numpy as np

arr = np.array([10, 20, 30])

new_arr = np.ones_like(arr)
print(new_arr)

[1 1 1]


In [40]:
arr = np.array([[10,20,30], [40,50,60]])

zroes = np.zeros(arr.shape)

print(zroes)


[[0. 0. 0.]
 [0. 0. 0.]]


In [43]:
arr = np.array([[1,2],[3,4]])

a = np.zeros(arr.shape)
b = np.zeros_like(arr)

print(a)
print("Hello")
print(b)

[[0. 0.]
 [0. 0.]]
Hello
[[0 0]
 [0 0]]


##Eng ko‘p ishlatiladigan dtype’lar
Type	Ma’nosi

###float32 / float64	o‘nlik son
###bool	True/False
###str / <U	string

In [50]:
arr = np.array([ False, 1, 3.5])

print(arr)
print(arr.dtype)

[0.  1.  3.5]
float64


##🔥 Type hierarchy (oddiy versiya)

###NumPy taxminan shunday qaraydi:

###bool → int → float → string

###Chapdagi type o‘ngdagiga aylanishi mumkin.

In [47]:
arr = np.array([3.4, "Mavlon", False, 3])

print(arr)
print(arr.dtype)

['3.4' 'Mavlon' 'False' '3']
<U32


In [51]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

print(arr * arr)

[[ 1.  4.  9.]
 [16. 25. 36.]]
