np.concatenate()
np.vstack()
np.hstack()
np.column_stack()

In [1]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.concatenate([a,b]))

[1 2 3 4 5 6]


In [ ]:
#2D Concatenate
a = np.array([
    [1,2],
    [3,4]
])

b = np.array([
    [5,6]
])

print(np.concatenate([a,b], axis=0)) #vertical rows qo‘shadi.
#a.shape -> (2,2)
#b.shape -> (1,2)
#Columns soni bir xil bo‘lishi kerak

[[1 2]
 [3 4]
 [5 6]]


In [7]:
a = np.array([
    [1,2],
    [3,4]
])

b = np.array([
    [5],
    [6]
])

np.concatenate([a,b], axis=1) #garizontal col qoshadi

array([[1, 2, 5],
       [3, 4, 6]])