In [1]:
import numpy as np

sales = np.array([
    [200, 150, 300],
    [220, 170, 310],
    [250, 160, 290],
    [210, 180, 305],
    [240, 175, 315],
    [260, 190, 330],
    [230, 185, 320]
])

print(sales)

[[200 150 300]
 [220 170 310]
 [250 160 290]
 [210 180 305]
 [240 175 315]
 [260 190 330]
 [230 185 320]]


          ProductA ProductB ProductC
Day1        200      150      300
Day2        220      170      310
Day3        250      160      290
...

In [4]:
shape = sales.shape
print(shape)

(7, 3)


In [ ]:
Product_Sales = np.sum(sales, axis=1) ##x va y o'qiga qarab tartiblaydi '
print(Product_Sales)

In [ ]:
Daily_Sales = np.sum(sales, axis=0) ##x va y o'qiga qarab tartiblaydi '
print(Daily_Sales)

In [3]:
Max_reniev_by_product= np.max(sales, axis=0) #eng katta Product revenue lar
Max_reniev= np.max(sales)


print(Max_reniev_by_product)
print(Max_reniev)

[260 190 330]
330


In [6]:
discount = sales - 50

print(discount)

[[150 100 250]
 [170 120 260]
 [200 110 240]
 [160 130 255]
 [190 125 265]
 [210 140 280]
 [180 135 270]]


In [8]:
product_A = sales[:,0]

print(product_A)

[200 220 250 210 240 260 230]


In [17]:
percentage_test = product_A * 0.85

print(percentage_test)

[170.  187.  212.5 178.5 204.  221.  195.5]


In [12]:
percentage = np.percentile(product_A, 100)
print(percentage)

260.0


In [41]:
day_3 = sales[3]

Avg = np.mean(day_3)

print(Avg)

231.66666666666666


In [47]:
day = np.mean(sales, axis= 1)

argmaximum =np.argmax(day)
print(day)
print(argmaximum)

[216.66666667 233.33333333 233.33333333 231.66666667 243.33333333
 260.         245.        ]
5


| Function      | Nima qaytaradi               |
| ------------- | ---------------------------- |
| `np.max()`    | eng katta qiymat             |
| `np.argmax()` | eng katta qiymatning index’i |


In [49]:
testing1 = np.mean(sales[5,0])
print(testing1)



260.0


In [50]:
day_avg = np.mean(sales, axis=1)

best_day_index = np.argmax(day_avg)

best_day_value = np.max(day_avg)

print(best_day_index + 1)
print(best_day_value)

6
260.0
