In [15]:
import numpy as np

print(np.random.randint(1, 10))

9


In [ ]:
#Bir nechta random son
arr = np.random.randint(1, 100, size=5)

print(arr)

[68 48 19 55 24]


In [30]:
#2D random array
arr = np.random.randint(1, 10, size=(3,3))

print(arr)

[[5 5 7]
 [2 7 9]
 [3 4 7]]
